title: <p align="center"> Gaurav Minocha </p>
logo: /assets/img/logo.png
description: <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/sajan-kedia-b06a6821/">LinkedIn</a> |
  <a href="https://github.com/sajankedia">GitHub</a>
  
  <br>   
  I'm working on Data Science, Big Data, Spark, Machine learning & NLP related problems.
  <br>
  </p>
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
